apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-service
  labels:
    app: {{ .Values.selector.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.selector.app }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
