name: lint yaml
on: [ push, pull_request ]
jobs: 
   lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v5
        - name: Helm lint
          run: |
           helm lint charts/*
