name: Deploy hello-world Helm Chart

on:
  push:
    branches: [main]
  pull_request:

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Helm Upgrade hello-world
      run: |
        helm upgrade --install hello-world ./charts/hello-world \
          --namespace hello-namespace \
          --create-namespace \
          -f values/prod-values.yaml
